<?php /** @var Klevu_Learning_Block_Tracking $this */ ?>
<?php $config = Mage::helper('klevu_search/config'); ?>
<?php if ($config->isExtensionConfigured()): ?>
<?php $cat_name = Mage::getSingleton('core/session')->getCategoryValue();?>
<?php if($cat_name!=' ') { ?>
    <script type="text/javascript">
    (function() {
        search_term = <?php echo Mage::getSingleton('core/session')->getCategoryValue(); ?>;
        if (search_term) {
            klevu_search_product_tracking = <?php echo $this->getJsonTrackingData() ?>;
            klevu_search_product_tracking.klevu_term = search_term;

            // Send the ajax request
            new Ajax.Request('//<?php echo $config->getAnalyticsUrl() ?>/analytics/productTracking', {
                method: "GET",
                parameters: klevu_search_product_tracking,

                // We need to remove the AJAX headers so the request does not get preflighted and break cross-origin request policy
                onCreate: function(response) {
                    var t = response.transport;
                    t.setRequestHeader = t.setRequestHeader.wrap(function(original, k, v) {
                        if (/^(accept|accept-language|content-language)$/i.test(k))
                            return original(k, v);
                        if (/^content-type$/i.test(k) &&
                            /^(application\/x-www-form-urlencoded|multipart\/form-data|text\/plain)(;.+)?$/i.test(v))
                            return original(k, v);
                        return;
                    });
                }
            });
        }
    })();
    </script>
<?php } ?>
<?php endif; ?>
