<?php /** @var Klevu_Search_Block_Adminhtml_Form_Field_Sync_Button $this */ ?>
<button id="<?php echo $this->getHtmlId() ?>" class="scalable" type="button">
    <span><?php echo $this->__($this->getButtonLabel()) ?></span>
</button>
<script type="text/javascript">
    $("<?php echo $this->getHtmlId() ?>").observe("click", function () {
        if(document.getElementById('klevu_search_developer_trigger_option')) {
            var triggeroptions = document.getElementById('klevu_search_developer_trigger_option').value;
            new Ajax.Request("<?php echo $this->getUrl('adminhtml/klevu_search/trigger_options_config'); ?>" + '?triggeroptions=' + triggeroptions, {
                method: 'POST',
                onComplete: function(data) {
                    setLocation("<?php echo $this->getDestinationUrl() ?>");
                }
            });
        } else {
            setLocation("<?php echo $this->getDestinationUrl() ?>");
        }
        
    });
</script>
