<?php /** @var Klevu_Search_Block_Adminhtml_Wizard_Configure_Store $this */ ?>
<?php $store = $this->getStore(); ?>
<?php echo $this->getChildHtml('messages') ?>
<div class="kuWizardSteps">
		<ol class="wizard-progress clearfix">
			<li class="active-step">
				<span class="step-name">Register/Login</span>
				<span class="visuallyhidden">Step </span><span class="step-num">&nbsp;</span>
			</li>
            <?php if(Mage::getSingleton('core/session')->getHideStep() != "yes") { ?>
			<li class="active-step">
				<span class="step-name">Select Plan</span>
				<span class="visuallyhidden">Step </span><span class="step-num">&nbsp;</span>
			</li>
            <?php } ?>
			<li class="active-step">
				<span class="step-name">Configure Store</span>
				<span class="visuallyhidden">Step </span><span class="step-num">&nbsp;</span>
			</li>
			<li>
				<span class="step-name">Finish & Sync</span>
				<span class="visuallyhidden">Step </span><span class="step-num">&nbsp;</span>
			</li>
		</ol>
	</div>
<form id="klevu_search_wizard_configure_store_form" action="<?php echo $this->getFormActionUrl() ?>" method="POST">
    <input type="hidden" name="form_key" value="<?php echo $this->getFormKey() ?>" />
    <fieldset class="fieldset">
        <table cellspacing="0" class="form-list">
            <tbody>
                <tr>
                    <td class="label"><label for="store"><?php echo $this->__("Select a Magento store you want to configure Klevu search for:") ?></label></td>
                    <td class="value">
                        <select name="store">
                            <option value=""></option>
                            <?php $data = $this->getStoreSelectData() ?>
                            <?php foreach ($data as $website => $groups): ?>
                                <optgroup label="<?php echo $this->escapeHtml($website) ?>"></optgroup>
                                <?php foreach ($groups as $group => $stores): ?>
                                    <optgroup label="&nbsp;&nbsp;<?php echo $this->escapeHtml($group) ?>">
                                        <?php foreach ($stores as $store): ?>
                                            <?php /** @var Mage_Core_Model_Store $store */ ?>
                                            <option value="<?php echo $store->getCode() ?>">&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $this->escapeHtml($store->getName()) ?></option>
                                        <?php endforeach; ?>
                                    </optgroup>
                                <?php endforeach; ?>
                            <?php endforeach; ?>
                        </select>
                    </td>
                </tr>

                <tr>
                    <td class="label"><label for="tax_enable"><?php echo $this->__("How do you want to display product prices in search?") ?></label></td>
                    <td class="value">
                        <select name="tax_enable" id="tax_enable">
                            <option value="2" selected="selected"><?php echo $this->__("Do not add tax in price as catalog prices entered by admin already include tax") ?></option>
                            <option value="0"><?php echo $this->__("Do not add tax in price as product prices are displayed without tax"); ?></option>
                            <option value="1"><?php echo $this->__("Add relevant tax in price as product prices need to be displayed with tax"); ?></option>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td class="label"><label for="secure_baseurl_enable"><?php echo $this->__("Which 'base URL' would you like to use for products in search results?<br/>(from System > Configuration > Web > Secure OR Unsecure > Base URL)") ?></label></td>
                    <td class="value">
                        <select name="secure_baseurl_enable" id="secure_base_enable">
                            <option value="0" selected="selected"><?php echo $this->__("Unsecure") ?></option>
                            <option value="1"><?php echo $this->__("Secure") ?></option>
                        </select>
                    </td>
                </tr>
            </tbody>
        </table>
    </fieldset>
    <div class="button-set">
        <button type="submit"><span><?php echo $this->__("Next") ?></span></button>
    </div>
</form>