<?php $config = Mage::helper('addtocart'); ?>
<?php if ($config->isAddtocartEnabled()) {?>
<script type="text/javascript">
function klevu_addtocart(id,url,qty) {
    var form_key = '<?php echo Mage::getSingleton('core/session')->getFormKey()?>';
    var url = '<?php echo Mage::getUrl('checkout/cart/add');?>'+'product/'+id+'/qty/'+qty+'/form_key/'+form_key;
    window.location.assign(url);
}

/* function klevu_uc_addtocartButton(){
      if( 'undefined' !== typeof klevu_userOptions ){
        klevu_userOptions.addToCartButton = 'Add to cart';
      } else{
        setTimeout( klevu_uc_addtocartButton, 300 );
      }
}
klevu_uc_addtocartButton(); */
</script>

<?php } ?>
