<?php /** @var Klevu_Search_Block_Adminhtml_Form_Information $this */ ?>
<div class="kuInfo">
   <div class="kuInfo-fLeft">
      <p><b><?php echo $this->__("Installed Version:") ?></b> <?php echo $this->__("{$this->getVersion()}") ?></br></p>
      <?php $check_plan = Mage::getModel("klevu_search/product_sync")->getFeatures();?>
      <?php if(empty($check_plan["errors"]) && !empty($check_plan)) { ?> 
        <p>
         <?php if(!empty($check_plan['user_plan_for_store'])) {?>
                <b><?php echo $this->__("My Current Plan:") ?></b>          
                <?php echo ucfirst($check_plan['user_plan_for_store']); 
         } ?> 
         <?php if(!empty($check_plan['upgrade_label'])) { ?>
             <button type='button' onClick=upgradeLink('<?php echo $check_plan["upgrade_url"]; ?>')><?php echo  $check_plan['upgrade_label']; ?></button>
             &nbsp;&nbsp;<a href="#" onClick="compareplan();"><?php echo $this->__("Compare Plans"); ?></a>
         <?php } ?>  
        </p>
      <?php } ?>
   </div>
   <div class="kuInfo-fRight">
      <ul>
         <li><b>Quick Links:</b></li>
         <li><a target="_blank" href="http://support.klevu.com/knowledgebase/integration-steps-for-magento/"><?php echo $this->__("Integration Steps");?></a></li>
         <li><a target="_blank" href="http://support.klevu.com/section/manuals/magento-manuals/migrate-klevu-search-from-staging-to-live/"><?php echo $this->__("Migrating from Staging to Live");?></a></li>
         <li><a target="_blank" href="http://support.klevu.com/faq/faqs/how-to-upgrade-my-current-plan/"><?php echo $this->__("How to upgrade plan?");?></a></li>
         <li><a target="_blank" href="http://box.klevu.com/"><?php echo $this->__("Klevu Merchant Center");?></a></li>
      </ul>
   </div>
   <div class="kuInfoClear"></div>
</div>
<div>
   <p><b><?php echo $this->__("Prerequisites:") ?></b></br>
      <?php echo $this->__("1. Ensure cron is running (<a href='http://support.klevu.com/knowledgebase/setup-a-cron/' target='_blank'>Click here</a> for more information on setting up a cron)") ?></br>
      <?php echo $this->__("2. Indices are uptodate (System > Index Management)") ?></br>
      <?php echo $this->__("3. Products should be enabled and have the visibility set to catalog and search") ?>
   </p>
</div>