<?php 
$config = Mage::helper('content'); 
if($config->isCmsSyncEnabledOnFront()) {?>
    <?php
        $url = Mage::getUrl('catalogsearch/result/')."?q=".Mage::helper('catalogsearch')->getEscapedQueryText();
        $url_content = Mage::getUrl('content/search')."?q=".Mage::helper('catalogsearch')->getEscapedQueryText();
    ?>
    <div class="page-title">
    <?php $selected_tab = Mage::app()->getRequest()->getModuleName(); ?>
        <a href="<?php echo $url; ?>" <?php if($selected_tab == "catalogsearch"){?> class="contentSelect" <?php } ?> ><?php echo $this->__('Products'); ?></a> | <a href="<?php echo $url_content; ?>" <?php if($selected_tab == "content"){?> class="contentSelect" <?php } ?>><?php echo $this->__('Other content'); ?></a>
    </div>
<?php } ?>