<?php /** @var Klevu_Search_Block_Adminhtml_Wizard_Config_Button $this */ ?>
<button id="<?php echo $this->getHtmlId() ?>" class="scalable" type="button">
    <span><?php echo $this->__("Start Configuration Wizard") ?></span>
</button>
<script type="text/javascript">
    $("<?php echo $this->getHtmlId() ?>").observe("click", function () {
        new Klevu.Search.Wizard({
            url: "<?php echo $this->getWizardUrl() ?>"
        });
    });
</script>
